services:
  bot:
    build: 
      context: .
      dockerfile: bot.Dockerfile
    restart: unless-stopped

  database:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: pizza311bot
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}