services:
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    volumes:
      - ./src:/app
    env_file:
      - .env
    command: python3 /app/main.py
    restart: unless-stopped
    container_name: pizzabot-bot

  database:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: pizza311bot
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306" # TODO: used for local DBeaver visualization, disable/comment in prod
    container_name: pizzabot-db
